src/project/account/urls.py
from django.urls import path
from . import views
from django.conf.urls import url


app_name = 'account'

urlpatterns = [
    path('login', views.login, name='login'),
]

src/project/examples/urls.py
from django.urls import path
from . import views
from . import api
from django.conf.urls import url


app_name = 'examples'

urlpatterns = [
    path('html', views.html, name='html'),
    path('py', views.py, name='py'),
    path('js', views.js, name='js'),


    path('api/add_item', api.agregar_al_carrito, name='add_to_cart'),
]

src/project/project/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.i18n import JavaScriptCatalog
from . import views
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _


urlpatterns = [
    path('admin/', admin.site.urls),
    # Internationalization in Javascript Code
    path( 'jsi18n/', JavaScriptCatalog.as_view(), name='javascript_catalog '),
    path( '', views.default, name='default' ),
    path( _('account/'), include('account.urls', namespace='account') ),
    path( _('examples/'), include( 'examples.urls', namespace='examples') ),
]

urlpatterns += i18n_patterns(
    path( '', views.default, name='default' ),
    path( _('account/'), include('account.urls', namespace='i18n_account')),
    path( _('examples/'), include('examples.urls', namespace='i18n_examples')),
)

src/project/account/models.py
from django.db import models

# Create your models here.

src/project/examples/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

src/project/account/forms.py
from django import forms
from django.utils.translation import (
    pgettext_lazy,
    ugettext_lazy as _
)

class LoginForm(forms.Form):
    username = forms.CharField(
        required = True,
        label = _('Usuario'),
        max_length = 100,
        widget = forms.TextInput(
            attrs={
                'class': 'input100'
            }
        )
    )

    password = forms.CharField(
        required = True,
        label = _('Contraseña'),
        max_length = 100,
        widget = forms.PasswordInput(
            attrs={
                'class': 'input100'
            }
        )
    )
    


    
    

src/project/examples/forms.py
from django import forms
from django.utils.translation import (
    pgettext_lazy as _c,
    ugettext_lazy as _,
)


class ExampleForm(forms.Form):
    cantidad = forms.CharField(
        required = False,
        label = _('Cantidad de artículos'),
        max_length = 3,
        widget = forms.TextInput(
            attrs={
                'class': 'input100'
            }
        )
    )

    estado = forms.CharField(
        required = False,
        label = _c('país', 'Estado'),
        max_length = 3,
        widget = forms.TextInput(
            attrs={
                'class': 'input100'
            }
        )
    )

    estatus = forms.CharField(
        required = False,
        label = _c('estatus', 'Estado'),
        max_length = 3,
        widget = forms.TextInput(
            attrs={
                'class': 'input100'
            }
        )
    )

src/project/account/views.py
from django.contrib import admin
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse
from . import forms
from django.utils import translation
from django.utils.translation import gettext as _, ngettext as _n

# Register your models here.

def login(request):
    template_name = "account/login.html"
    form = forms.LoginForm( request.POST or None, use_required_attribute=False )
    
    if request.method == 'POST':
        if form.is_valid():
            return redirect(reverse('i18n_examples:html'))

    context = {
        'form': form,
    }
    return render(request, template_name, context)

src/project/examples/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.contrib import admin
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse
from . import forms
from django.utils import translation
from django.utils.translation import gettext as _, ngettext as _n

# Create your views here.

def html(request):
    form = forms.ExampleForm( request.POST or None, use_required_attribute=False )
    
    context = {
        'hello_word': _('Hola Mundo'),
    }
    return render(request, "examples/example_html.html", context)


def py(request):
    form = forms.ExampleForm( request.POST or None, use_required_attribute=False )
    
    context = {
        'form': form,
        'hello_word': _('Hola Mundo'),
    }
    return render(request, "examples/example_py.html", context)


def js(request):
    form = forms.ExampleForm( request.POST or None, use_required_attribute=False )
    
    context = {
        'form': form
    }
    return render(request, "examples/example_js.html", context)

src/project/project/views.py
from django.shortcuts import HttpResponseRedirect
from django.urls import reverse

# Register your models here.

def default(request):
    return HttpResponseRedirect(reverse('i18n_account:login'))

src/project/templates/base_login.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
<head>
	<title>
        {% block title %}{% endblock title %}
    </title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
    <!--https://colorlib.com/wp/template/login-form-v14/-->	
        <link rel="icon" type="image/png" href={% static 'images/icons/favicon.ico' %}>
        <link rel="stylesheet" type="text/css" href={% static 'libs/vendor/bootstrap/css/bootstrap.min.css' %}>
        <link rel="stylesheet" type="text/css" href={% static 'fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}> {% comment %} 
        <link rel="stylesheet" type="text/css" href={% static 'fonts/Linearicons-Free-v1.0.0/icon-font.min.css' %}>
        <link rel="stylesheet" type="text/css" href={% static 'libs/vendor/animate/animate.css' %}>	
        <link rel="stylesheet" type="text/css" href={% static 'libs/vendor/css-hamburgers/hamburgers.min.css' %}>
        <link rel="stylesheet" type="text/css" href={% static 'libs/vendor/animsition/css/animsition.min.css' %}>
        <link rel="stylesheet" type="text/css" href={% static 'libs/vendor/select2/select2.min.css' %}>	
        <link rel="stylesheet" type="text/css" href={% static 'libs/vendor/daterangepicker/daterangepicker.css' %}> {% endcomment %}
        <link rel="stylesheet" type="text/css" href={% static 'css/base_login/util.css' %}>
        <link rel="stylesheet" type="text/css" href={% static 'css/base_login/main.css' %}>
        {% block css %}
        {% endblock css %}
</head>
<body class='bg-dark'>
	{% block content %}
    {% endblock content %}
</body>
    <!--https://colorlib.com/wp/template/login-form-v14/-->	
        <script src={% static 'libs/vendor/jquery/jquery-3.2.1.min.js' %}></script>
        {% comment %} <script src={% static 'libs/vendor/animsition/js/animsition.min.js' %}></script>
        <script src={% static 'libs/vendor/bootstrap/js/popper.js' %}></script>
        <script src={% static 'libs/vendor/bootstrap/js/bootstrap.min.js' %}></script>
        <script src={% static 'libs/vendor/select2/select2.min.js' %}></script>
        <script src={% static 'libs/vendor/daterangepicker/moment.min.js' %}></script>
        <script src={% static 'libs/vendor/daterangepicker/daterangepicker.js' %}></script>
        <script src={% static 'libs/vendor/countdowntime/countdowntime.js' %}></script> {% endcomment %}
        <script src={% static 'js/base_login/main.js' %}></script>
        <script src="/jsi18n/"></script>
    {% block scripts %}
    {% endblock scripts %}
</html>

src/project/templates/examples/example_html.html
{% extends 'base_login.html' %}
{% load static i18n %}

{% block css %}
    <link rel="stylesheet" href="{% static 'libs/vendor/jquery.steps/jquery.steps.css' %}">
{% endblock css %}



{% block title %}
    {% trans "Ejemplo HTML" %}
{% endblock title %}


{% block content %}
    <h1 class="login100-form-title text-center fs-50 m-t-20">HTML</h1>
    <div class="container m-t-50">
        <div id="steps">


            <h3>{% trans "Traducción simple" %}</h3>
            <section>
                <div class="row">
                    <!--CONTROLS-->
                    <div class="col-12">
                        <div class="wrap-login100-no-w p-5"> 
                            <span class="login100-form-title p-b-32 no-block text-center fs-50">

                                {% trans "Hola Mundo!" %}

                            </span>
                        </div>  
                    </div>
                </div>
            </section>


            <h3>{% trans "Traducción con variables" %}</h3>
            <section>
                <div class="row">
                    <!--CONTROLS-->
                    <div class="col-12">
                        <div class="wrap-login100-no-w p-5"> 
                            <span class="login100-form-title p-b-32 no-block text-center fs-50">

                                {% blocktranslate %}Utilizando blocktranslate: "{{ hello_word }}"{% endblocktranslate %}

                            </span>
                        </div>  
                    </div>
                </div>
            </section>


            <h3>{% trans "Palabras ambiguas" %}</h3>
            <section>
                <div class="row">
                    <div class="col-6">
                        <div class="wrap-login100-no-w p-5">
                            <span class="login100-form-title p-b-32 no-block text-center fs-50">

                                {% trans "Estado" context "país"%}
                                <p>país</p>

                            </span>
                        </div>  
                    </div>
                    <div class="col-6">
                        <div class="wrap-login100-no-w p-5">
                            <span class="login100-form-title p-b-32 no-block text-center fs-50">

                                {% trans "Estado" context "estatus"%}
                                <p>estatus</p>

                            </span>
                        </div>  
                    </div>
                    <div class="flex-sb-m w-full p-b-48">
                    </div>
                </div>
            </section>

            
            <h3>{% trans "Identificador" %}</h3>
            <section>
                <div class="row">
                    <!--CONTROLS-->
                    <div class="col-12">
                        <div class="wrap-login100-no-w p-5"> 
                            <span class="login100-form-title p-b-32 no-block text-center fs-50">

                                {% trans "dialogo_largo_01" %}

                            </span>
                        </div>  
                    </div>
                </div>
            </section>

        </div>
    </div>
{% endblock content %}

{% block scripts %}
    <script>
        var nextURL = "{% url 'i18n_examples:py' %}"

    </script>
    <script src="{% static 'libs/vendor/jquery.steps/jquery.steps.js' %}"></script>
    <script src="{% static 'js/examples/example.js' %}"></script>
{% endblock scripts %}

src/project/templates/examples/example_js.html
{% extends 'base_login.html' %}
{% load static i18n %}

{% block css %}
    <link rel="stylesheet" href="{% static 'libs/vendor/jquery.steps/jquery.steps.css' %}">
{% endblock css %}



{% block title %}
    {% trans "Ejemplo JS" %}
{% endblock title %}


{% block content %}
    <h1 class="login100-form-title text-center fs-50 m-t-20">JS</h1>
    <div class="container m-t-50">
        <div id="steps">
        
            <h3>{% trans "Traducción simple" %}</h3>
            <section>
                <div class="row">
                    <div class="col-12">
                        <div class="wrap-login100-no-w p-5">
                            <span id="hola_mundo" class="replace_translate login100-form-title p-b-32 no-block text-center fs-50">
                                    
                                Hola Mundo
                                
                            </span>
                        </div>  
                    </div>
                </div>
            </section>


            <h3>{% trans "Palabras ambiguas" %}</h3>
            <section>
                <div class="row">
                    <div class="col-6">
                        <div class="wrap-login100-no-w p-5"> 
                            <span id="pais" class="replace_translate login100-form-title p-b-32 no-block text-center fs-50">

                                Estado
                                <p>país</p>

                            </span>
                        </div>  
                    </div>
                    <div class="col-6">
                        <div class="wrap-login100-no-w p-5">
                            <span id="estatus" class="replace_translate login100-form-title p-b-32 no-block text-center fs-50">

                                Estado
                                <p>estatus</p>

                            </span>
                        </div>  
                    </div>
                </div>
            </section>


            <h3>{% trans "Singular o plural" %}</h3>
            <section>
                <div class="row">
                    <div class="col-6">
                        <div class="wrap-login100-no-w p-5">
                            <span class="login100-form-title p-b-32">
                                {% trans "Singular o plural" %}
                            </span>
                            <div class="m-b-36">
                                <span class="txt1 p-b-11">
                                    {{ form.cantidad.label }}
                                </span>
                                <div class="wrap-input100 validate-input" >
                                    {{ form.cantidad }}
                                    <span class="focus-input100"></span>
                                </div>
                            </div>

                            <div class="flex-sb-m w-full p-b-48">
                            </div>

                            <div class="container-login100-form-btn">
                                <button id="carrito" class="replace_translate register100-form-btn btn-block" type="button">
                                    {% trans "Agregar al carrito" %}
                                </button>
                            </div>
                                
                        </div>  
                    </div>
                            
                    <!--Response-->
                    <div class="col-6 bg-light border border-dark rounded response-area custom-scrollable">
                                
                    </div>
                </div>
            </section>
        </div>
    </div>
{% endblock content %}

{% block scripts %}
    <script>
        var nextURL = "{% url 'i18n_account:login' %}"
        $('#form').on('submit', function(e){
            e.preventDefault();
            $.get("{% url 'examples:add_to_cart' %}",
            {cantidad: $('#id_cantidad').val()}
            ,function(response){
                $('.response-area').append($('<p>', { text: response['message'] }));
            });
        });
    </script>
    <script src="{% static 'libs/vendor/jquery.steps/jquery.steps.js' %}"></script>
    <script src="{% static 'js/examples/example.js' %}"></script>
    <script src="{% static 'js/examples/example_js.js' %}"></script>
{% endblock scripts %}

src/project/templates/examples/example_py.html
{% extends 'base_login.html' %}
{% load static i18n %}

{% block css %}
    <link rel="stylesheet" href="{% static 'libs/vendor/jquery.steps/jquery.steps.css' %}">
{% endblock css %}



{% block title %}
    {% trans "Ejemplo PY" %}
{% endblock title %}


{% block content %}
    <h1 class="login100-form-title text-center fs-50 m-t-20">PYTHON</h1>
    <div class="container m-t-50">
        <div id="steps">
            <h3>{% trans "Traducción simple" %}</h3>
            <section>
                <div class="row">
                    <!--CONTROLS-->
                    <div class="col-12">
                        <div class="wrap-login100-no-w p-5">
                            <span class="login100-form-title p-b-32 no-block text-center fs-50">

                                {{ hello_word }}
                            
                            </span>
                        </div>  
                    </div>
                </div>
            </section>

            
            <h3>{% trans "Palabras ambiguas" %}</h3>
            <section>
                <div class="row">
                    <div class="col-6">
                        <div class="wrap-login100-no-w p-5"> 
                            <span class="login100-form-title p-b-32 no-block text-center fs-50">

                                {{ form.estado.label }}
                                <p>país</p>

                            </span>
                        </div>  
                    </div>
                    <div class="col-6">
                        <div class="wrap-login100-no-w p-5">
                            <span class="login100-form-title p-b-32 no-block text-center fs-50">

                                {{ form.estatus.label }}
                                <p>estatus</p>

                            </span>
                        </div>  
                    </div>
                </div>
            </section>


            <h3>{% trans "Singular o plural" %}</h3>
            <section>
                <form id="form" action="{% url 'examples:add_to_cart' %}" method="get" >
                    {% csrf_token %}
                    <div class="row">
                        <!--CONTROLS-->
                        <div class="col-6">
                            <div class="wrap-login100-no-w p-5">
                                <span class="login100-form-title p-b-32">
                                    {% trans "Singular o plural" %}
                                </span>
                                <div class="m-b-36">
                                    <span class="txt1 p-b-11">
                                        {{ form.cantidad.label }}
                                    </span>
                                    <div class="wrap-input100 validate-input" >
                                        {{ form.cantidad }}
                                        <span class="focus-input100"></span>
                                    </div>
                                </div>

                                <div class="flex-sb-m w-full p-b-48">
                                </div>

                                <div class="container-login100-form-btn">
                                    <button id="add2cart" class="register100-form-btn btn-block" type="submit">
                                        {% trans "Agregar al carrito" %}
                                    </button>
                                </div>
                                
                            </div>  
                        </div>
                            
                        <!--Response-->
                        <div class="col-6 bg-light border border-dark rounded response-area custom-scrollable">
                                
                        </div>
                    </div>
                </form>
            </section>
        </div>
    </div>
{% endblock content %}

{% block scripts %}
    <script>
        var nextURL = "{% url 'i18n_examples:js' %}"
    </script>
    <script src="{% static 'libs/vendor/jquery.steps/jquery.steps.js' %}"></script>
    <script src="{% static 'js/examples/example.js' %}"></script>   
    <script>
        $('#form').on('submit', function(e){
            e.preventDefault();
            $.get("{% url 'examples:add_to_cart' %}",
            {cantidad: $('#id_cantidad').val()}
            ,function(response){
                $('.response-area').append($('<p>', { text: response['message'] }));
                $('#id_cantidad').val('');
            });
        });
    </script>
{% endblock scripts %}